MODULE constantes
  INTEGER, PARAMETER :: mi=50, nj=50, lk=50,itermax=1000, nsolid = 1
  INTEGER, PARAMETER :: SGL=SELECTED_REAL_KIND(P=6,R=37)
  INTEGER, PARAMETER :: DBL=SELECTED_REAL_KIND(P=15,R=300)
  REAL(kind=DBL),    PARAMETER :: cero=0._DBL, visc_solido = 1.e80_DBL
END MODULE constantes
